webpersonal/product/models.py
from webpersonal import db

class Product(db.Model):
    __tablename__ = 'products'
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(100))
    description = db.Column(db.Text)
    price = db.Column(db.Float)
    stock = db.Column(db.String(5))

    def __init__(self, title, description, price, stock):
        self.title = title
        self.description = description
        self.price = price
        self.stock = stock

    def __repr__(self):
        return f'Product: {self.title}'

        

webpersonal/product/views.py
from flask import render_template, Blueprint, request, redirect, url_for

from webpersonal.product.models import Product

from webpersonal import db

product = Blueprint('product', __name__)

@product.route('/product/')
@product.route('/product/index')
def index():
    products = Product.query.all()
    db.session.commit
    return render_template('product/index.html', products = products)

@product.route('/product/create')
def create():
    return render_template('product/create.html')

@product.route('/product/insert', methods=['POST'])
def insert():
    title = request.form.get('title')
    description = request.form.get('description')
    price = request.form.get('price')
    stock = request.form.get('stock')

    product = Product(title, description, price, stock)

    db.session.add(product)
    db.session.commit()

    return redirect(url_for('product.index'))

@product.route('/product/edit/<int:id>')
def edit(id):
    product = Product.query.get_or_404(id)
    return render_template('product/edit.html', product=product)

@product.route('/product/update/<int:id>', methods=['POST'])
def update(id):
    product = Product.query.get_or_404(id)
    product.title = request.form.get('title')
    product.description = request.form.get('description')
    product.price = request.form.get('price')
    product.stock = request.form.get('stock')

    db.session.add(product)
    db.session.commit()

    return redirect(url_for('product.index'))

@product.route('/product/delete/<int:id>')
def delete(id):
    product = Product.query.get_or_404(id)
    db.session.delete(product)
    db.session.commit()

    return redirect(url_for('product.index'))


@product.route('/product/view/')
def store():
    products = Product.query.all()
    db.session.commit
    return render_template('product/see.html', products = products)

webpersonal/templates/product/create.html
{% extends './base.html' %}

{% block title %} Agregar Producto {%endblock%}

{% block content %}

<h2 class="mt-4">Agregar nuevo Producto</h2>

<form action="{{ url_for('product.insert')}}" method="POST" >
    <label for="title">Titulo</label><br>
    <input type="text" id="title" name="title"><br>
    <label for="description">Descripción</label><br>
    <textarea name="description" id="description" cols="50" rows="10"></textarea><br>
    <label for="price">Precio</label><br>
    <input type="text" id="price" name="price"><br>
    <label for="stock">Stock</label><br>
    <input type="number" id="stock" name="stock"><br>
    <br>
    <input type="submit" value="Guardar" class="btn btn-success">
</form>

<a href="{{url_for('product.index')}}">
    <img src="https://img.icons8.com/ios-filled/50/000000/circled-left.png"/>
</a>


{% endblock %}

webpersonal/templates/product/edit.html
{% extends './base.html' %}

{% block title %} Nuevo proyecto {%endblock%}

{% block content %}
<form action="{{ url_for('product.update', id=product.id)}}" method="POST">
    <label for="title">Titulo</label><br>
    <input type="text" id="title" name="title" value="{{product.title}}"><br>
    <label for="description">Descripción</label><br>
    <textarea name="description" id="description" cols="50" rows="10">{{product.description}}</textarea><br>
    <label for="price">Precio</label><br>
    <input type="text" id="price" name="price" value="{{product.price}}"><br>
    <br>
    <label for="stock">Stock</label><br>
    <input type="number" id="stock" name="stock" value="{{product.stock}}"><br>
    <br>
    
    <input type="submit" value="Guardar">
</form>

<a href="{{url_for('product.index')}}">
    <img src="https://img.icons8.com/ios-filled/50/000000/circled-left.png"/>
</a>

{% endblock %}

webpersonal/templates/product/index.html
{% extends './base.html'%}

{% block title %} Mis productos {% endblock %}

{% block content %}

<h1 class="title mt-4">Lista de Productos</h1>
<br>
<div class="btn-new">
    <a href="{{url_for('product.create')}}">Agregar producto</a>
</div>

    <table class="table table-hover container">
        <tr class="table-info">
            <th>Titulo</th>
            <th>Descripción</th>
            <th>Precio</th>
            <th>Existencia</th>
            <th></th>
        </tr>
        {% for product in products %}
        <tr class="table-dark">
            <td>{{product.title}}</td>
            <td>{{product.description}}</td>
            <td>$ {{product.price}}</td>
            <td>{{product.stock}}</td>
            <td>
                <a href="{{url_for('product.edit', id=product['id'])}}" class="btn btn-info">Editar</a>
                <a href="{{url_for('product.delete', id=product['id'])}}" class="btn btn-danger">Eliminar</a>
            </td>
        
        </tr>

        {%endfor%}
    </table>

{% endblock %}