webpersonal/customer/models.py
from webpersonal import db

class Customer(db.Model):
    __tablename__ = 'customers'
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(100))
    phone = db.Column(db.String(15))
    city = db.Column(db.String(50))
    

    def __init__(self, name, phone, city):
        self.name = name
        self.phone = phone
        self.city = city

    def __repr__(self):
        return f'{self.name}, {self.phone}'

webpersonal/customer/views.py
from flask import render_template, Blueprint, request, redirect, url_for
# from webpersonal.project.models import proyectos
from webpersonal.customer.models import Customer

from webpersonal import db

customer = Blueprint('customer', __name__)

@customer.route('/customer/')
@customer.route('/customer/index')
def index():
    customers = Customer.query.all()
    db.session.commit

    return render_template('customer/index.html', customers = customers)

@customer.route('/customer/create')
def create():
    return render_template('customer/create.html')

@customer.route('/customer/insert', methods=['POST'])
def insert():
    name = request.form.get('name')
    phone = request.form.get('phone')
    city = request.form.get('city')

    customer = Customer(name, phone, city)

    db.session.add(customer)
    db.session.commit()

    return redirect(url_for('customer.index'))

@customer.route('/project/edit/<int:id>')
def edit(id):
    customer = Customer.query.get_or_404(id)
    return render_template('customer/edit.html', customer=customer)

@customer.route('/customer/update/<int:id>', methods=['POST'])
def update(id):
    customer = Customer.query.get_or_404(id)
    customer.name = request.form.get('name')
    customer.phone = request.form.get('phone')
    customer.city = request.form.get('city')

    db.session.add(customer)
    db.session.commit()

    return redirect(url_for('customer.index'))

@customer.route('/customer/delete/<int:id>')
def delete(id):
    customer = Customer.query.get_or_404(id)
    db.session.delete(customer)
    db.session.commit()

    return redirect(url_for('customer.index'))

webpersonal/templates/customer/create.html
{% extends './base.html' %}

{% block title %} Nuevo proyecto {%endblock%}

{% block content %}
<br>
<h2>Nuevo Cliente</h2>
<br>
<form action="{{ url_for('customer.insert')}}" method="POST">
    <label for="name">Nombre</label><br>
    <input type="text" id="name" name="name"><br>
    <label for="phone">Telefono</label><br>
    <input type="phone" id="phone" name="phone"><br>
    <label for="city">Ciudad</label><br>
    <input type="text" id="city" name="city"><br>


    <input type="submit" value="Guardar" class="btn btn-success">
</form>

<a href="{{url_for('customer.index')}}">
    <img src="https://img.icons8.com/ios-filled/50/000000/circled-left.png"/>
</a>


{% endblock %}

webpersonal/templates/customer/edit.html
{% extends './base.html' %}

{% block title %} Nuevo proyecto {%endblock%}

{% block content %}
<h2>Crear nuevo proyecto</h2>

<form action="{{ url_for('customer.update', id=customer.id)}}" method="POST">
    <label for="name">Titulo</label><br>
    <input type="text" id="name" name="name" value="{{customer.name}}"><br>
    <label for="phone">Telefono</label><br>
    <input type="phone" id="phone" name="phone" value="{{customer.phone}}"><br>
    <label for="city">Ciudad</label><br>
    <input type="text" id="city" name="city" value="{{customer.city}}"><br>

    <input class="btn btn-success mb-4" type="submit" value="Guardar">
</form>

{% endblock %}

webpersonal/templates/customer/index.html
{% extends './base.html'%}

{% block title %} Clientes {% endblock %}

{% block content %}

<h1 class="title mt-4">Lista de Clientes</h1>


<br>
<div class="btn-new">
    <a href="{{url_for('customer.create')}}">Agregar cliente</a>
</div>

    <table class="table table-hover container">
        <tr class="table-info">
            <th>Titulo</th>
            <th>Descripción</th>
            <th>Ciudad</th>
            <th></th>
        </tr>
        {% for customer in customers %}
        <tr class="table-dark">
            <td>{{customer.name}}</td>
            <td>{{customer.phone}}</td>
            <td>{{customer.city}}</td>
            <td>
                <a class="btn btn-info" href="{{url_for('customer.edit', id=customer['id'])}}">Editar</a>
                <a class="btn btn-danger" href="{{url_for('customer.delete',id=customer['id'])}}">Eliminar</a>
            </td>
        </tr>

        {%endfor%}
    </table>

{% endblock %}