webpersonal/sale/models.py
from sqlalchemy.orm import backref
from webpersonal import db

class Sale(db.Model):
    __tablename__ = 'sales'
    id = db.Column(db.Integer, primary_key = True)
    date = db.Column(db.Date)
    total = db.Column(db.Float)
    metodo_pago = db.Column(db.String(55))
    product_id = db.Column(db.Integer, db.ForeignKey('products.id'))
    producto = db.relationship('Product', backref=db.backref('productos', lazy=True))
    customer_id = db.Column(db.Integer, db.ForeignKey('customers.id'))
    cliente = db.relationship('Customer', backref=db.backref('clientes', lazy=True))
    

    def __init__(self, date, total, metodo_pago, product_id, customer_id):
        self.date = date
        self.total = total
        self.metodo_pago = metodo_pago
        self.product_id = product_id
        self.customer_id = customer_id
        

    def __repr__(self):
        return f'{self.total}, {self.date}'

        
    

webpersonal/sale/views.py
from flask import render_template, Blueprint, request, redirect, url_for
from webpersonal.customer.models import Customer
from webpersonal.product.models import Product

from webpersonal.sale.models import Sale

from webpersonal import db

sale = Blueprint('sale', __name__)


@sale.route('/sale/')
@sale.route('/sale/index')
def index():
    sales = Sale.query.all()
    db.session.commit()
    productos = Product.query.all()
    db.session.commit()
    clientes = Customer.query.all()
    db.session.commit()
    return render_template('sale/index.html', sales = sales, productos = productos, clientes = clientes)

@sale.route('/sale/create')
def create():
    sales = Sale.query.all()
    db.session.commit()
    productos = Product.query.all()
    db.session.commit()
    clientes = Customer.query.all()
    db.session.commit()
    return render_template('sale/create.html', sales=sales, productos=productos, clientes = clientes)

@sale.route('/sale/insert', methods=['POST'])
def insert():
    date = request.form.get('date')
    total = request.form.get('total')
    metodo_pago = request.form.get('metodo_pago')
    product_id = request.form.get('product_id')
    customer_id = request.form.get('customer_id')

    sale = Sale(date, total, metodo_pago, product_id, customer_id)

    db.session.add(sale)
    db.session.commit()

    return redirect(url_for('sale.index'))

@sale.route('/sale/edit/<int:id>')
def edit(id):
    sale = Sale.query.get_or_404(id)
    productos = Product.query.all()
    db.session.commit()
    clientes = Customer.query.all()
    db.session.commit()
    
    return render_template('sale/edit.html', sale=sale, productos=productos, clientes=clientes)

@sale.route('/sale/update/<int:id>', methods=['POST'])
def update(id):
    sale = Sale.query.get_or_404(id)
    sale.date = request.form.get('date')
    sale.total = request.form.get('total')
    sale.metodo_pago = request.form.get('metodo_pago')
    sale.product_id = request.form.get('product_id')
    sale.customer_id = request.form.get('customer_id')

    db.session.add(sale)
    db.session.commit()

    return redirect(url_for('sale.index'))

@sale.route('/sale/delete/<int:id>')
def delete(id):
    sale = Sale.query.get_or_404(id)
    db.session.delete(sale)
    db.session.commit()

    return redirect(url_for('sale.index'))


@sale.route('/home/')
def currency():
    sales = Sale.query.all()
    db.session.commit

    # Método para ganancias obtenidas(total)
    suma = 0

    for sale in sales:
        suma += sale.total

    # Método para el total de ventas
    total_ventas = 0
    for sale in sales:
        total_ventas += 1

    return render_template('home.html', sales=sales, suma=suma, total_ventas = total_ventas)

webpersonal/templates/sale/create.html
{% extends './base.html' %}

{% block title %} Agregar Venta {%endblock%}

{% block content %}
<h2 class="mt-4">Agregar nueva Venta</h2>
<br>
<form action="{{ url_for('sale.insert')}}" method="POST" >
    <label for="date">Fecha de Venta</label><br>
    <input type="date" id="date" name="date"><br>

    <label for="metodo_pago">Método de pago</label><br>
    <select name="metodo_pago" id="metodo_pago">
        <option value="Tarjeta de Crédito">Tarjeta de Crédito</option>
        <option value="Efectivo">Efectivo</option>
    </select>
    <br>
    <label for="product_id">Producto</label><br>
    <select name="product_id" id="product_id">
        {% for producto in productos %}
            <option value="{{producto.id}}">{{producto.title}}</option>

        {%endfor%}
    </select>
    <br>
    <label for="customer_id">Cliente</label><br>
    <select name="customer_id" id="customer_id">
        {% for cliente in clientes %}
            <option value="{{cliente.id}}">{{cliente.name}}</option>

        {%endfor%}
    </select>
    <br>
    <label for="total">Total Pagado</label><br>
    <input type="text" id="total" name="total"><br>


    <br>
    <input type="submit" value="Guardar" class="btn btn-success">
</form>

<a href="{{url_for('sale.index')}}">
    <img src="https://img.icons8.com/ios-filled/50/000000/circled-left.png"/>
</a>


{% endblock %}

webpersonal/templates/sale/edit.html
{% extends './base.html' %}

{% block title %} Nuevo proyecto {%endblock%}

{% block content %}
<br>
<h2>Modifica datos</h2>
<br>
<form action="{{ url_for('sale.update', id=sale.id)}}" method="POST">
    <label for="date">Fecha de Venta</label><br>
    <input type="date" id="date" name="date" value="{{sale.date}}"><br>

    <label for="metodo_pago">Método de pago</label><br>
    <select name="metodo_pago" id="metodo_pago">
        <option selected disabled value="{{sale.metodo_pago}}">{{sale.metodo_pago}}</option>
        <option value="Tarjeta de Crédito">Tarjeta de Crédito</option>
        <option value="Efectivo">Efectivo</option>
    </select>
    <br>

    <label for="product_id">Id Producto</label><br>
    <select name="product_id" id="product_id">
        <option selected disabled class="opcion-desactivada">{{sale.producto.title}}</option>
        {% for producto in productos %}
            <option value="{{producto.id}}">{{producto.title}}</option>

        {%endfor%}
    </select>
    <br>
    <label for="customer_id">Id cliente</label><br>
    <select name="customer_id" id="customer_id">
        <option disabled select value="{{clientes.id}}">{{sale.cliente.name}}</option>
        {% for cliente in clientes %}
            <option value="{{cliente.id}}">{{cliente.name}}</option>

        {%endfor%}
    </select>
<br>
    <label for="total">Total Pagado</label><br>
    <input type="number" id="total" name="total" value="{{sale.total}}"><br>
    <br>
    
    <input type="submit" value="Guardar" class="btn btn-info">
</form>

<a href="{{url_for('sale.index')}}">
    <img src="https://img.icons8.com/ios-filled/50/000000/circled-left.png"/>
</a>

{% endblock %}

webpersonal/templates/sale/index.html
{% extends './base.html'%}

{% block title %} Mis productos {% endblock %}

{% block content %}
<div class="contenedor-titulo"></div>
<h1 class="title mt-4">Ventas listadas</h1>
<br>
<div class="btn-new">
    <a href="{{url_for('sale.create')}}">Agregar Venta</a>
</div>

    <table class="table table-hover container">
        <tr class="table-info">
            <th>Fecha de venta</th>
            <th>Metodo de Pago</th>
            <th>Producto vendido</th>
            <th>Cliente</th>
            <th>Total pagado</th>
            <th></th>
        </tr>
        {% for sale in sales %}
        <tr class="table-dark ">
            <td>{{sale.date}}</td>
            <td>{{sale.metodo_pago}}</td>
            <td>{{sale.producto.title}}</td>
            <td>{{sale.cliente.name}}</td>
            <td>$ {{sale.total}}</td>
            <td>
                <a href="{{url_for('sale.edit', id=sale['id'])}}" class="btn btn-info">Editar</a>
                <a href="{{url_for('sale.delete', id=sale['id'])}}" class="btn btn-danger">Eliminar</a>
            </td>
        </tr>

        {%endfor%}
    </table>

{% endblock %}