webpersonal/sale/views.py
from flask import render_template, Blueprint, request, redirect, url_for
from webpersonal.customer.models import Customer
from webpersonal.product.models import Product

from webpersonal.sale.models import Sale

from webpersonal import db

sale = Blueprint('sale', __name__)


@sale.route('/sale/')
@sale.route('/sale/index')
def index():
    sales = Sale.query.all()
    db.session.commit()
    productos = Product.query.all()
    db.session.commit()
    clientes = Customer.query.all()
    db.session.commit()
    return render_template('sale/index.html', sales = sales, productos = productos, clientes = clientes)

@sale.route('/sale/create')
def create():
    sales = Sale.query.all()
    db.session.commit()
    productos = Product.query.all()
    db.session.commit()
    clientes = Customer.query.all()
    db.session.commit()
    return render_template('sale/create.html', sales=sales, productos=productos, clientes = clientes)

@sale.route('/sale/insert', methods=['POST'])
def insert():
    date = request.form.get('date')
    total = request.form.get('total')
    metodo_pago = request.form.get('metodo_pago')
    product_id = request.form.get('product_id')
    customer_id = request.form.get('customer_id')

    sale = Sale(date, total, metodo_pago, product_id, customer_id)

    db.session.add(sale)
    db.session.commit()

    return redirect(url_for('sale.index'))

@sale.route('/sale/edit/<int:id>')
def edit(id):
    sale = Sale.query.get_or_404(id)
    productos = Product.query.all()
    db.session.commit()
    clientes = Customer.query.all()
    db.session.commit()
    
    return render_template('sale/edit.html', sale=sale, productos=productos, clientes=clientes)

@sale.route('/sale/update/<int:id>', methods=['POST'])
def update(id):
    sale = Sale.query.get_or_404(id)
    sale.date = request.form.get('date')
    sale.total = request.form.get('total')
    sale.metodo_pago = request.form.get('metodo_pago')
    sale.product_id = request.form.get('product_id')
    sale.customer_id = request.form.get('customer_id')

    db.session.add(sale)
    db.session.commit()

    return redirect(url_for('sale.index'))

@sale.route('/sale/delete/<int:id>')
def delete(id):
    sale = Sale.query.get_or_404(id)
    db.session.delete(sale)
    db.session.commit()

    return redirect(url_for('sale.index'))


@sale.route('/home/')
def currency():
    sales = Sale.query.all()
    db.session.commit

    # Método para ganancias obtenidas(total)
    suma = 0

    for sale in sales:
        suma += sale.total

    # Método para el total de ventas
    total_ventas = 0
    for sale in sales:
        total_ventas += 1

    return render_template('home.html', sales=sales, suma=suma, total_ventas = total_ventas)

webpersonal/views.py
# from webpersonal import app
from flask import render_template, Blueprint

from webpersonal.customer.models import Customer
from webpersonal.sale.models import Sale
from webpersonal.product.models import Product

# Importamos db para poder usar la base de datos 
from webpersonal import db

# Definimos nuestros blueprints
customer = Blueprint('customer', __name__)
sale = Blueprint('sale', __name__)
product = Blueprint('product', __name__)


base = Blueprint('base', __name__)

@base.route('/') # Ruta de la función
@base.route('/home') #Ruta de la función 
def home(): # Función principal
    customers = Customer.query.all()
    db.session.commit
    sales = Sale.query.all()
    db.session.commit
    products = Product.query.all()
    db.session.commit

    # Método para ganancias obtenidas(total)
    suma_ganancias = 0

    for sale in sales:
        suma_ganancias += sale.total

    # Método para el total de ventas
    total_ventas = 0
    for sale in sales:
        total_ventas += 1

    # Método para el número de clientes
    total_clientes = 0
    for customer in customers:
        total_clientes += 1

    # Método para el número de productos
    total_productos = 0
    for product in products:
        total_productos += 1

    return render_template('home.html', customers = customers, suma_ganancias = suma_ganancias, total_ventas=total_ventas, total_clientes=total_clientes, total_productos=total_productos)

webpersonal/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Título dinámico -->
    <title>Web Store - {% block title%} {% endblock %}</title> 
    <!-- Referencias al CSS personalizado y el boostrap -->
    <link rel="stylesheet" href="https://bootswatch.com/5/minty/bootstrap.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">

</head>
<body>
    <header class="navbar navbar-dark sticky-top bg-blue-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{{url_for('base.home')}}"> WebStore</a>
    
    </header>
    
    <!-- Menú de navegación -->
    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{url_for('base.home')}}">
                                <span data-feather="home"></span>
                                Escritorio
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('sale.index')}}">
                                <span data-feather="file"></span>
                                Ventas
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('product.index')}}">
                                <span data-feather="shopping-cart"></span>
                                Productos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('customer.index')}}">
                                <span data-feather="users"></span>
                                Clientes
                            </a>
                        </li>
    
                </div>
            </nav>
    
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                
                <!-- Aquí se coloca el contenido de las demás plantillas -->
                {% block content %}

                {% endblock %}

                
            </main>
            
        </div>
    </div>
    
    <!-- Scripts requeridos para la ejecución del proyecto -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
</body>
</html>

webpersonal/templates/home.html
{% extends 'base.html' %}

{% block title%} Home {% endblock %}

{% block content %}
<h1 class="mt-4">Web Store</h1>
<br>
<p>WebStore es una aplicación para gestionar un negocio de una manera sencilla y potente. </p>
<br>


<!-- Carrusel de imágenes -->
<div id="carouselExampleFade" class="carousel slide carousel-fade container" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://images.unsplash.com/photo-1487014679447-9f8336841d58?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1605&q=80"
                class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="https://images.unsplash.com/photo-1599658880436-c61792e70672?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"
                class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1115&q=80"
                class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<br>
<br>

<!-- Datos generales del sistema -->
<div class="contenedor-tarjetas">
    <div class="tarjeta ">
        
            <h4>Ganancias obtenidas</h2>
        
            <h1 class="">${{suma_ganancias}}</h1>
        
    </div>

    <div class="tarjeta" >
            <h4>Total de ventas</h4>
            <h1 class="card-title">{{total_ventas}}</h1>
    </div>

    <div class="tarjeta" >
        
            <h4>Número de Clientes</h4>
        
            <h1 class="card-title">{{total_clientes}}</h1>
    </div>

    <div class="tarjeta" >
        
            <h4>Número de productos</h4>
        
            <h1 class="card-title">{{total_productos}}</h1>
    </div>

</div>

<br>












{% endblock %}